[workspace]
resolver = "2"
members = ["crates/om-core", "crates/om-render", "crates/om-app"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yobud/open-md"
rust-version = "1.78"

[workspace.dependencies]
pulldown-cmark = { version = "0.12", default-features = false, features = ["html"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
thiserror = "1"
anyhow = "1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"

[profile.dev]
opt-level = 1
